import { SIMILARITY_MATCH_COUNT, EMBEDDING_MODEL_NAME, SIMILARITY_THRESHOLD } from "../constants.js";
import { openai, supabase } from "../config.js";

export async function retrieveSimilarDocs(query) {
    // Create vector embeddings based on user query
    const embeddingResponse = await openai.embeddings.create({
        model: EMBEDDING_MODEL_NAME,
        input: query,
    });

    // Vector generated by OpenAI
    const embedding = embeddingResponse.data[0].embedding;

    // Retrieve similar docs from supabase based on the embeddings
    const { data: documents, error: matchError } = await supabase.rpc(
        'match_documents',
        {
            query_embedding: embedding,
            match_count: SIMILARITY_MATCH_COUNT,
            match_threshold: SIMILARITY_THRESHOLD, 
        }
    );

    if (matchError) {
        throw new Error(`Failed to fetch docs from supabase. Error: ${matchError}`);
    }

    return documents;
}